### ISSUE TITLE
FIx IllegalArgumentException on Checkpointing

### ISSUE THREAD

**Issue by DifferentSC** [snuspl/mist#1111]
Currently, when checkpointing the following exception is raised:

> SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
java.lang.IllegalArgumentException: Can not set edu.snu.mist_exp.source.type.DataEvent field edu.snu.mist_exp.source.type.DataEventWithTimestamp.dataEvent to edu.snu.mist_exp.source.type.DataEventWithTimestamp
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
        at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
        at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75)
        at java.lang.reflect.Field.set(Field.java:764)
        at com.rits.cloning.Cloner.cloneObject(Cloner.java:450)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
        at com.rits.cloning.Cloner$1.deepClone(Cloner.java:104)
        at com.rits.cloning.FastClonerLinkedList.clone(FastClonerLinkedList.java:19)
        at com.rits.cloning.Cloner.fastClone(Cloner.java:115)
        at com.rits.cloning.Cloner.cloneInternal(Cloner.java:417)
        at com.rits.cloning.Cloner.deepClone(Cloner.java:302)
        at edu.snu.mist.core.operators.ApplyStatefulOperator.getStateSnapshot(ApplyStatefulOperator.java:97)
        at edu.snu.mist.core.operators.ApplyStatefulOperator.processLeftCheckpoint(ApplyStatefulOperator.java:108)
        at edu.snu.mist.core.task.OperatorOutputEmitter.sendCheckpoint(OperatorOutputEmitter.java:108)
        at edu.snu.mist.core.task.OperatorOutputEmitter.emitCheckpoint(OperatorOutputEmitter.java:193)
        at edu.snu.mist.core.operators.MapOperator.processLeftCheckpoint(MapOperator.java:78)
        at edu.snu.mist.core.task.OperatorOutputEmitter.sendCheckpoint(OperatorOutputEmitter.java:108)
        at edu.snu.mist.core.task.OperatorOutputEmitter.emitCheckpoint(OperatorOutputEmitter.java:193)
        at edu.snu.mist.core.operators.FilterOperator.processLeftCheckpoint(FilterOperator.java:79)
        at edu.snu.mist.core.task.OperatorOutputEmitter.sendCheckpoint(OperatorOutputEmitter.java:108)
        at edu.snu.mist.core.task.OperatorOutputEmitter.emitCheckpoint(OperatorOutputEmitter.java:193)
        at edu.snu.mist.core.operators.MapOperator.processLeftCheckpoint(MapOperator.java:78)
        at edu.snu.mist.core.task.NonBlockingQueueSourceOutputEmitter.process(NonBlockingQueueSourceOutputEmitter.java:93)
        at edu.snu.mist.core.task.NonBlockingQueueSourceOutputEmitter.processAllEvent(NonBlockingQueueSourceOutputEmitter.java:73)
        at edu.snu.mist.core.task.DefaultQueryImpl.processAllEvent(DefaultQueryImpl.java:122)
        at edu.snu.mist.core.task.groupaware.DefaultGroupImpl.processAllEvent(DefaultGroupImpl.java:237)
        at edu.snu.mist.core.task.groupaware.DefaultGroupImpl.processAllEvent(DefaultGroupImpl.java:219)
        at edu.snu.mist.core.task.groupaware.eventprocessor.AffinityRunnable.run(AffinityRunnable.java:82)
        at net.openhft.affinity.AffinityThreadFactory$1.run(AffinityThreadFactory.java:62)
        at java.lang.Thread.run(Thread.java:748)

We need to fix this problem.

**Comment by taegeonum** [comment]
This was addressed by #1153
